### ISSUE TITLE
The Example From Getting Started with a Server Give Me An Error: unresolved import `hyper_util::rt::TokioIo`

### ISSUE THREAD

**Issue by flukis** [hyperium/hyperium.github.io#105]
An example how to use hyper on server in this page give me an error: [page](https://hyper.rs/guides/1/server/hello-world/) here's the error message showed to me:

```
unresolved import `hyper_util::rt::TokioIo`
the item is gated behind the `tokio` feature
```

This is my cargo.toml:

```toml

[package]
name = "repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }


```
